import { Park } from "@app/core/models/park";
import { mockAreas } from "./areas";

export const mockParks: Park[] = [
  {
    id: 1,
    name: "xotopar",
    lat: 41.01293504282219,
    lng: 28.95420994690147,
    location: "xotopar location ------------------- ------------------------ ----- ---------------- -----------",
    areas: mockAreas,
    statusUpdateTime: Date.now(),
    emptySpace: 20,
    occupiedSpace: 5,
    reservedSpace: 4,
    minPrice: 10,
    maxPrice: 50,
    avgPrice: 20,
    extras: [
      "extra1",
      "extra2",
      "extra3",
      "extraaaaaaaaaaaaaaaaaaaaa4",
    ]
  },
  {
    id: 2,
    name: "xotopar",
    lat: 41.03293504282219,
    lng: 28.93420994690147,
    location: "xotopar location ------------------- ------------------------ ----- ---------------- -----------",
    areas: mockAreas,
    statusUpdateTime: Date.now(),
    emptySpace: 20,
    occupiedSpace: 5,
    reservedSpace: 4,
    minPrice: 10,
    maxPrice: 50,
    avgPrice: 20,
    extras: [
      "extra1",
      "extra2",
      "extra3",
      "extraaaaaaaaaaaaaaaaaaaaa4",
    ]
  },
  {
    id: 3,
    name: "xotopar",
    lat: 41.01746840384831,
    lng: 28.933095597536038,
    location: "xotopar location ------------------- ------------------------ ----- ---------------- -----------",
    areas: mockAreas,
    statusUpdateTime: Date.now(),
    emptySpace: 20,
    occupiedSpace: 5,
    reservedSpace: 4,
    minPrice: 10,
    maxPrice: 50,
    avgPrice: 20,
    extras: [
      "extra1",
      "extra2",
      "extra3",
      "extraaaaaaaaaaaaaaaaaaaaa4",
    ]
  }
  ,
  {
    id: 4,
    name: "xotopar",
    lat: 41.024850638335835,
    lng: 29.01257481506545,
    location: "xotopar location ------------------- ------------------------ ----- ---------------- -----------",
    areas: mockAreas,
    statusUpdateTime: Date.now(),
    emptySpace: 20,
    occupiedSpace: 5,
    reservedSpace: 4,
    minPrice: 10,
    maxPrice: 50,
    avgPrice: 20,
    extras: [
      "extra1",
      "extra2",
      "extra3",
      "extraaaaaaaaaaaaaaaaaaaaa4",
    ]
  }
  ,
  {
    id: 5,
    name: "xotopar",
    lat: 40.99648279881782,
    lng:  29.05291523864898,
    location: "xotopar location ------------------- ------------------------ ----- ---------------- -----------",
    areas: mockAreas,
    statusUpdateTime: Date.now(),
    emptySpace: 20,
    occupiedSpace: 5,
    reservedSpace: 4,
    minPrice: 10,
    maxPrice: 50,
    avgPrice: 20,
    extras: [
      "extra1",
      "extra2",
      "extra3",
      "extraaaaaaaaaaaaaaaaaaaaa4",
    ]
  }
  ,
  {
    id: 6,
    name: "xotopar",
    lat: 40.97536090806648,
    lng:  28.978757523805115,
    location: "xotopar location ------------------- ------------------------ ----- ---------------- -----------",
    areas: mockAreas,
    statusUpdateTime: Date.now(),
    emptySpace: 20,
    occupiedSpace: 5,
    reservedSpace: 4,
    minPrice: 10,
    maxPrice: 50,
    avgPrice: 20,
    extras: [
      "extra1",
      "extra2",
      "extra3",
      "extraaaaaaaaaaaaaaaaaaaaa4",
    ]
  }
  ,
  {
    id: 7,
    name: "xotopar",
    lat: 41.00490375179632,
    lng:  28.93652882507385,
    location: "xotopar location ------------------- ------------------------ ----- ---------------- -----------",
    areas: mockAreas,
    statusUpdateTime: Date.now(),
    emptySpace: 20,
    occupiedSpace: 5,
    reservedSpace: 4,
    minPrice: 10,
    maxPrice: 50,
    avgPrice: 20,
    extras: [
      "extra1",
      "extra2",
      "extra3",
      "extraaaaaaaaaaaaaaaaaaaaa4",
    ]
  },
  {
    id: 8,
    name: "xotopar",
    lat: 41.04738076198703,
    lng: 29.02115788391214,
    location: "xotopar location ------------------- ------------------------ ----- ---------------- -----------",
    areas: mockAreas,
    statusUpdateTime: Date.now(),
    emptySpace: 20,
    occupiedSpace: 5,
    reservedSpace: 4,
    minPrice: 10,
    maxPrice: 50,
    avgPrice: 20,
    extras: [
      "extra1",
      "extra2",
      "extra3",
      "extraaaaaaaaaaaaaaaaaaaaa4",
    ]
  }
  ,
  {
    id: 9,
    name: "xotopar",
    lat: 41.02446212030708,
    lng: 29.072312974243374,
    location: "xotopar location ------------------- ------------------------ ----- ---------------- -----------",
    areas: mockAreas,
    statusUpdateTime: Date.now(),
    emptySpace: 20,
    occupiedSpace: 5,
    reservedSpace: 4,
    minPrice: 10,
    maxPrice: 50,
    avgPrice: 20,
    extras: [
      "extra1",
      "extra2",
      "extra3",
      "extraaaaaaaaaaaaaaaaaaaaa4",
    ]
  }
];
